la guidance link added
FoodStandardsAgency/register-a-food-business-service pull request #332
Opened 2023-05-11 08:23 UTC by Joe-Cun-Civica

added laguidance link parts to the notifcations and submissions service

2023-05-15 21:00 UTC, ernestas-leliuga requested changes
Prior to merging, several issues will need to be addressed, as well as unit tests

2023-05-15 21:00 UTC, ernestas-leliuga commented on src/services/notifications.service.js
> +     if (lcContactConfig.standards.local_guidance_link) {
It should be "hygieneandstandards" rather than "standards"

2023-05-15 21:00 UTC, ernestas-leliuga commented on src/services/notifications.service.js
>        lcContactConfig.hygiene.new_authority_name ||
The hygiene one is missing

2023-05-15 21:00 UTC, ernestas-leliuga commented on src/api/submissions/submissions.service.js
> +              local_guidance_link: urlLcConfig.local_guidance_link,
The parameter name is different, the frontend uses local_council_guidance_link, while here it is local_guidance_link

2023-05-15 21:00 UTC, ernestas-leliuga commented on src/services/notifications.service.js
> +         lcContactConfig.standards.local_guidance_link;
The parameter name is different, the frontend uses local_council_guidance_link, while here it is local_guidance_link

2023-06-23 14:49 UTC, simon-says-test approved these changes

2023-06-23 14:52 UTC, ernestas-leliuga approved these changes

2023-06-26 13:54 UTC, merged